name: Setup WP-Env
description: Full setup - dependencies and WordPress environment
runs:
  using: composite
  steps:
    - name: Setup dependencies
      uses: ./.github/actions/setup-deps

    - name: Setup WP-Env
      uses: ./.github/actions/setup-wp-env
